from config.base import *
from config.debug import *
from config.stage0 import (
    ARENA_SIZE_X, ARENA_SIZE_Y, ARENA_HEIGHT, MIN_START_GOAL_DIST
)

from config.stage1 import (
    STAGE1_N_OBSTACLES, STAGE1_RADIUS, STAGE1_HEIGHT
)
from config import load_config

__all__ = [
    'load_config',

    'PYB_FREQ', 'CTRL_FREQ', 'MAX_STEPS',
    'VX_MAX', 'VY_MAX', 'VZ_MAX', 'YAW_RATE_MAX',
    'N_RAYS', 'RAY_LENGTH',
    'SEED', 'N_ENVS',
    'PPO_PARAMS',
    'REWARD_SUCCESS', 'REWARD_CRASH', 'REWARD_OUT_OF_BOUNDS_EXTRA', 'REWARD_COLLISION_EXTRA', 'REWARD_WAYPOINT',
    'REWARD_PROGRESS_SCALE', 'REWARD_VELOCITY_SCALE',
    'REWARD_HEADING_SCALE', 'REWARD_ACTION_SMOOTHNESS_SCALE',
    'REWARD_YAW_PENALTY_SCALE', 'REWARD_PROXIMITY_THRESHOLD',
    'REWARD_PROXIMITY_SCALE', 'REWARD_BOUNDARY_THRESHOLD', 'REWARD_BOUNDARY_SCALE',
    'REWARD_BOUNDARY_OUTWARD_SCALE', 'REWARD_OBSTACLE_APPROACH_SCALE',
    'REWARD_NEAR_GOAL_RADIUS', 'REWARD_NEAR_GOAL_PROGRESS_EPS', 'REWARD_NEAR_GOAL_STALL_SCALE',
    'REWARD_STEP_PENALTY',
    'REWARD_EXPLORATION_BONUS', 'REWARD_EFFICIENCY_BONUS',
    'REWARD_EFFICIENCY_SCALE', 'EXPLORATION_GRID_SIZE',
    'SAFETY_SHIELD_ENABLED', 'SAFETY_SHIELD_SOFT_CLEARANCE', 'SAFETY_SHIELD_HARD_CLEARANCE',
    'SAFETY_SHIELD_AVOID_GAIN', 'SAFETY_SHIELD_BRAKE_GAIN', 'SAFETY_SHIELD_MAX_YAW',
    'SAFETY_SHIELD_TOPK', 'SAFETY_SHIELD_VERTICAL_GAIN', 'SAFETY_SHIELD_HARD_BRAKE_SCALE',
    'MIN_CLEARANCE', 'SUCCESS_DIST', 'SUCCESS_HOLD_RADIUS', 'SUCCESS_HOLD_STEPS',
    'GOAL_VEL_SOFT_RADIUS', 'GOAL_VEL_MIN_SCALE',
    'WAYPOINT_THRESHOLD', 'OUT_OF_BOUNDS_EPS',
    'BOUNDARY_VEL_SOFT_MARGIN', 'BOUNDARY_VEL_MIN_SCALE',

    'ARENA_SIZE_X', 'ARENA_SIZE_Y', 'ARENA_HEIGHT', 'MIN_START_GOAL_DIST',
    'STAGE1_N_OBSTACLES', 'STAGE1_RADIUS', 'STAGE1_HEIGHT',

    'DEBUG_MODE', 'LOG_REWARD_COMPONENTS', 'LOG_NAVIGATION_METRICS',
    'LOG_PATH_FOLLOWING_METRICS', 'LOG_EPISODE_METRICS',
    'LOG_EXTENDED_EPISODE_METRICS', 'LOG_TIMEOUT_ANALYSIS',
    'LOG_ACTION_STATS', 'LOG_PPO_INTERNALS',
    'LOG_INTERVAL_EPISODES', 'LOG_INTERVAL_STEPS',
    'LOG_TENSORBOARD', 'LOG_CSV', 'LOG_CSV_PATH',
    'CROSS_TRACK_ERROR_THRESHOLD', 'HOVERING_SPEED_THRESHOLD',
    'SPINNING_YAW_THRESHOLD', 'TIMEOUT_NEAR_GOAL_THRESHOLD',
    'TIMEOUT_STUCK_MOVEMENT_THRESHOLD'
]