"""
Base configuration - common parameters for all stages.
"""

# ===== SIMULATION PARAMETERS =====
PYB_FREQ = 240  # Physics simulation frequency (Hz)
CTRL_FREQ = 30  # Control frequency (Hz) - how often agent makes decisions
MAX_STEPS = 1200  # Episode length in control steps (1200/30 = 40 seconds)

# ===== DRONE CONTROL PARAMETERS =====
VX_MAX = 1.2
VY_MAX = 1.2
VZ_MAX = 0.8  # Was 0.8
YAW_RATE_MAX = 0.8
MAX_COMMAND_SPEED = 0.0  # 0 disables vector-norm speed clipping.
VELOCITY_TARGET_LOOKAHEAD_STEPS = 3.0

# ===== RAYCASTS =====
N_RAYS = 20  # Was 16
RAY_LENGTH = 5.0

# ===== TRAINING PARAMETERS =====
SEED = 42
N_ENVS = 8  # Number of parallel environments

# ===== PPO HYPERPARAMETERS =====
PPO_PARAMS = {
    "learning_rate": 1e-4,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "policy": "MlpPolicy",
    "use_sde": True,
    "sde_sample_freq": 8,
}

# ===== REWARD PARAMETERS (COMMON) =====
REWARD_SUCCESS = 500
REWARD_CRASH = -2200.0
REWARD_TIMEOUT = -200.0
REWARD_OUT_OF_BOUNDS_EXTRA = -400.0
REWARD_COLLISION_EXTRA = 0.0
REWARD_WAYPOINT = 50.0
REWARD_PROGRESS_SCALE = 10.0
REWARD_VELOCITY_SCALE = 4.0
REWARD_HEADING_SCALE = 5.0
REWARD_ACTION_SMOOTHNESS_SCALE = 0.5
REWARD_YAW_PENALTY_SCALE = 8.0
REWARD_PROXIMITY_THRESHOLD = 3.0
REWARD_PROXIMITY_SCALE = 6.0
REWARD_BOUNDARY_THRESHOLD = 1.4
REWARD_BOUNDARY_SCALE = 11.0
REWARD_BOUNDARY_OUTWARD_SCALE = 12.0
REWARD_OBSTACLE_APPROACH_SCALE = 3.5
REWARD_NEAR_GOAL_RADIUS = 1.5
REWARD_NEAR_GOAL_PROGRESS_EPS = 0.01
REWARD_NEAR_GOAL_PROGRESS_SCALE = 0.0
REWARD_NEAR_GOAL_STALL_SCALE = 45.0
REWARD_NEAR_GOAL_AWAY_SCALE = 0.0
REWARD_NEAR_GOAL_SPEED_SCALE = 0.0
REWARD_NEAR_GOAL_SPEED_TARGET = 0.35
REWARD_NEAR_GOAL_CAPTURE_RADIUS = 0.0
REWARD_NEAR_GOAL_CAPTURE_SPEED_TARGET = 0.0
REWARD_NEAR_GOAL_CAPTURE_SCALE = 0.0
REWARD_TIMEOUT_NEAR_GOAL_RADIUS = 0.0
REWARD_TIMEOUT_NEAR_GOAL_SCALE = 0.0
REWARD_TIMEOUT_REGRESSION_RADIUS = 0.0
REWARD_TIMEOUT_REGRESSION_SCALE = 0.0
REWARD_STEP_PENALTY = 0.0015
REWARD_EXPLORATION_BONUS = 0.0
REWARD_EFFICIENCY_BONUS = True
REWARD_EFFICIENCY_SCALE = 200.0
EXPLORATION_GRID_SIZE = 1.0

# ===== SAFETY SHIELD (ACTION FILTER) =====
SAFETY_SHIELD_ENABLED = False
SAFETY_SHIELD_SOFT_CLEARANCE = 1.2
SAFETY_SHIELD_HARD_CLEARANCE = 0.7
SAFETY_SHIELD_AVOID_GAIN = 0.6
SAFETY_SHIELD_BRAKE_GAIN = 0.6
SAFETY_SHIELD_MAX_YAW = 0.55
SAFETY_SHIELD_TOPK = 3
SAFETY_SHIELD_VERTICAL_GAIN = 0.3
SAFETY_SHIELD_HARD_BRAKE_SCALE = 0.5

# ===== COMMON PARAMETERS =====
MIN_CLEARANCE = 1.0
SUCCESS_DIST = 0.45
SUCCESS_HOLD_RADIUS = 0.45
SUCCESS_HOLD_STEPS = 1
SUCCESS_HOLD_MAX_SPEED = 0.0
GOAL_VEL_SOFT_RADIUS = 0.0
GOAL_VEL_MIN_SCALE = 1.0
GOAL_AWAY_VEL_SOFT_RADIUS = 0.0
GOAL_AWAY_VEL_MIN_SCALE = 1.0
WAYPOINT_THRESHOLD = 0.3
OUT_OF_BOUNDS_EPS = 0.05
BOUNDARY_VEL_SOFT_MARGIN = 0.9
BOUNDARY_VEL_MIN_SCALE = 0.05
USE_ENHANCED_OBS = False
ENHANCED_OBS_BRAKE_ACCEL = 0.75
ENHANCED_OBS_BOUNDARY_REF = 2.0
ENHANCED_OBS_RAY_DELTA_SCALE = 1.0
PHYSICAL_ARENA_WALLS = False
PHYSICAL_ARENA_WALLS_INCLUDE_ENDS = True
PHYSICAL_ARENA_WALL_THICKNESS = 0.08
PHYSICAL_ARENA_WALL_HEIGHT = None
PHYSICAL_ARENA_WALL_ALPHA = 0.10
PHYSICAL_ARENA_CEILING = False
REWARD_OBSTACLE_HARD_THRESHOLD = 0.0
REWARD_OBSTACLE_HARD_SCALE = 0.0
REWARD_NEAR_GOAL_BOUNDARY_SCALE = 0.0
REWARD_NEAR_GOAL_BOUNDARY_THRESHOLD = 0.0
