"""
Debug and monitoring configuration.
"""

# ===== DEBUG MODE =====
DEBUG_MODE = True

# ===== REWARD COMPONENTS LOGGING =====
LOG_REWARD_COMPONENTS = True

# ===== NAVIGATION METRICS =====
LOG_NAVIGATION_METRICS = True

# ===== PATH FOLLOWING METRICS =====
LOG_PATH_FOLLOWING_METRICS = True
CROSS_TRACK_ERROR_THRESHOLD = 0.5

# ===== EPISODE METRICS =====
LOG_EPISODE_METRICS = True

# ===== EXTENDED EPISODE METRICS =====
LOG_EXTENDED_EPISODE_METRICS = True
HOVERING_SPEED_THRESHOLD = 0.2
SPINNING_YAW_THRESHOLD = 0.5

# ===== TIMEOUT ANALYSIS =====
LOG_TIMEOUT_ANALYSIS = True
TIMEOUT_NEAR_GOAL_THRESHOLD = 2.0
TIMEOUT_STUCK_MOVEMENT_THRESHOLD = 5.0

# ===== ACTION STATS =====
LOG_ACTION_STATS = True

# ===== PPO INTERNALS =====
LOG_PPO_INTERNALS = True

# ===== LOGGING FREQUENCY =====
LOG_INTERVAL_EPISODES = 10
LOG_INTERVAL_STEPS = 5000
LOG_TENSORBOARD = True
LOG_CSV = True
LOG_CSV_PATH = "logs/debug_metrics.csv"
