from .base import *

ARENA_SIZE_X = 15.0
ARENA_SIZE_Y = 15.0
ARENA_HEIGHT = 5.0
MIN_START_GOAL_DIST = 8.0

RRT_MAX_ITER = 300
RRT_STEP_SIZE = 1.5
RRT_GOAL_BIAS = 0.3
RRT_GOAL_THRESHOLD = 0.8
RRT_REWIRE_RADIUS = 2.5
RRT_COLLISION_RESOLUTION = 0.3
RRT_MAX_SEGMENT_LENGTH = 5.0